apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: shopnow-jsree
type: Opaque
stringData:
  MONGODB_URI: mongodb://jeyashreenirmalvasanpadmapriya_db_user:Mongopw261997@mongo-0.mongo-headless.shopnow-jsree.svc.cluster.local:27017/shopnow?authSource=admin


